apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: current-analytics-tech-tls
spec:
  secretName: current-analytics-tech
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: current-analytics.tech
  dnsNames:
    - current-analytics.tech
    - www.current-analytics.tech
  acme:
    config:
      - http01: 
          ingressClass: nginx
        domains:
          - current-analytics.tech
          - www.current-analytics.tech